Feat/hub server ch
Sparta-3TM/3TM pull request #17
Opened 2024-09-10 09:03 UTC by CZ-punk

2024-09-10 09:08 UTC, CZ-punk commented
.

2024-09-10 13:34 UTC, lukeydokey requested changes

2024-09-10 13:34 UTC, lukeydokey commented on hub-server/src/main/resources/application.yml
이거 키는 새로 발급받으시고 깃헙엔 안올리는 방향으로 하셔야할것같아요 저희 슬랙에서만 공유하고

2024-09-11 01:36 UTC, CZ-punk commented
로컬에서만 테스트하고 버릴거라 그냥 올렸었는데 불편하시면 알고리즘 끝나고 다시 올릴게요

2024-09-11 02:00 UTC, closed without merging